plugins {
    id "com.android.application"
}

android {
    namespace "com.example.wtoolsample"
    compileSdk 35

    defaultConfig {
        applicationId "com.example.wtoolsample"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    packaging {
        jniLibs {
            keepDebugSymbols += ["**/libwtoolsdk.so"]
        }
    }
}

dependencies {
    implementation files("libs/wtoolsdk.jar")
}
