plugins {
    id "com.android.application"
}

android {
    namespace "com.example.wtoolsample"
    compileSdk 35

    defaultConfig {
        applicationId "com.example.wtoolsample"
        minSdk 16
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        debug {
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging true
            keepDebugSymbols += ["**/libwtoolsdk.so"]
        }
    }
}

dependencies {
    implementation files("libs/wtoolsdk.jar")
}
